### ISSUE TITLE
underrun execution issue

### ISSUE THREAD

**Issue by WolfieWerewolf** [skoppe/spasm#4]
Hi Mate.. I just compiled and attempted to load the underrun example.. It compiled fine but when I hit the webpack-dev instance I got the following on the console:

![image](https://user-images.githubusercontent.com/10762757/52515179-b88d7580-2bee-11e9-873b-09b698a4bda2.png)

I'm not sure where this is coming from.  Can you re-produce this or is it a dev-env issue on my side?

Thanks

/W

**Comment by skoppe** [comment]
I have had this error before, it is a missing import. Essentially the implementation for _d_array_cast_len is missing, and it is not supplied by the js glue code.

I need to look into the code. Will do later today.

**Comment by WolfieWerewolf** [comment]
Cool..  I just wondered if it was a known issue or just my dev-env.  Thatnks...

**Comment by skoppe** [comment]
I fixed the underrun example and released v0.1.7

Will look into the other examples later this weekend to check if they work.

The reason were some breaking changes and me not updating the examples.

**Comment by WolfieWerewolf** [comment]
Excellent and I completely understand... I really appreciate your help as I learn your bindings.

**Comment by WolfieWerewolf** [comment]
Ok so I've tested this with your latest and I am still seeing the same error as above.  I went ahead and added the missing function signature with a console.log implementation to the jsExports object to see what happens after it gets called and this is the result:

```js
let jsExports = {
    _d_arraycast_len: ()=> { console.log("_d_arraycast_len called")},
    onOutOfMemoryError: () => abort("Out of memory exception"),
```
![image](https://user-images.githubusercontent.com/10762757/52538009-af61ed00-2d43-11e9-9a9f-8f83280305d2.png)

It's not a concern for me right now, I have lots of other stuff to test, but I thought you would want to know about this.
